[package]
name = "wsajaaiqiqiqjqja/aura-gateway"  # 👈 حتماً به جای username نام کاربری خود در Wasmer را بگذارید
version = "0.1.0"
description = "AURA Gateway VLESS Proxy"
readme = "README.md"

[[modules]]
name = "aura-app"
source = "."
abi = "wasi"

[[commands]]
name = "server"
module = "aura-app"
runner = "docker"

[deploy]
[[deploy.services]]
image = "."
build = "Dockerfile"
architecture = "amd64"
# 👈 اضافه کردن این خط به Wasmer دستور می‌دهد کانتینر داکر را دقیقا طبق تنظیمات خودش لود کند
entrypoint = ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"]

[[deploy.services.ports]]
port = 8000
handler = "http"